--Creación de Usuarios

--SELECT * FROM DBA_USERS; para ver los usuarios

--Administradores
CREATE USER admin1 IDENTIFIED BY admin1
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 15M ON USERS;

CREATE USER admin2 IDENTIFIED BY admin2
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 15M ON USERS;

CREATE USER admin3 IDENTIFIED BY admin3
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 15M ON USERS;

--Gerentes de Productor
CREATE USER mcdonalds IDENTIFIED BY mcdonalds
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 15M ON USERS;

CREATE USER subway IDENTIFIED BY subway
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 15M ON USERS;

CREATE USER pizzahut IDENTIFIED BY pizzahut
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 15M ON USERS;

--Gerentes de Proveedor
CREATE USER yummy IDENTIFIED BY yummy
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 15M ON USERS;

CREATE USER ubigo IDENTIFIED BY ubigo
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 15M ON USERS;

CREATE USER delfoodve IDENTIFIED BY delfoodve
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 15M ON USERS;

--Transportistas
CREATE USER jackson IDENTIFIED BY jackson
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 15M ON USERS;

CREATE USER leonardo IDENTIFIED BY leonardo
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 15M ON USERS;

CREATE USER alejandro IDENTIFIED BY alejandro
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 15M ON USERS;

--Usuarios
CREATE USER ricardo IDENTIFIED BY ricardo
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 15M ON USERS;

CREATE USER jose IDENTIFIED BY jose
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 15M ON USERS;

CREATE USER david IDENTIFIED BY david
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 15M ON USERS;

--Asignar roles a los usuarios

--Administradores
GRANT administrador TO admin1;
GRANT administrador TO admin2;
GRANT administrador TO admin3;

--Gerentes de Productor
GRANT gerente_productor TO mcdonalds;
GRANT gerente_productor TO subway;
GRANT gerente_productor TO pizzahut;

--Gerentes de Proveedor
GRANT gerente_proveedor TO yummy;
GRANT gerente_proveedor TO ubigo;
GRANT gerente_proveedor TO delfoodve;

--Transportistas
GRANT transportista TO jackson;
GRANT transportista TO leonardo;
GRANT transportista TO alejandro;

--Usuarios
GRANT usuario TO ricardo;
GRANT usuario TO jose;
GRANT usuario TO david;

